#ifndef MLC_STATUS_H
#define MLC_STATUS_H

typedef enum {
    MLC_STATUS_SUCCESS = 0,
    MLC_STATUS_INVALID_DIMENSIONS,
    MLC_STATUS_INVALID_ARGUMENT,
    MLC_STATUS_MEMORY_ALLOCATION_FAILURE,
    MLC_STATUS_OUT_OF_BOUNDS_INDEX,
    MLC_STATUS_DIMENSIONS_MISMATCH,
    MLC_STATUS_FILE_ERROR,
    MLC_STATUS_PARSE_ERROR
} MLCStatus;

#endif //MLC_STATUS_H